### ISSUE TITLE
Php seems unnecessary

### ISSUE THREAD

**Issue by JustInToCoding** [TimmNL/magicmirror#1]
Php seems unnecessary, perhaps you could just enable cross-site scripting on the browser?

**Comment by TimmNL** [comment]
I'll look in to that :)

**Comment by JustInToCoding** [comment]
Here is the solution: http://www.html5rocks.com/en/tutorials/security/content-security-policy/

**Comment by TimmNL** [comment]
If you want to use the calendar on the mirror, a server is needed. If not, you can use it without.
